apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos-cluster-30042 
  namespace: dev
spec:
  paasJobAnnotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
    prometheus.io/path: /nacos/actuator/prometheus
    prometheus.io/scrape: 'true'
    prometheus.io/port: "8848"
  nodePort: 30042
  type: cluster
  env:
   - name: JVM_XMS
     value: 1g
   - name: NACOS_AUTH_ENABLE
     value: 'false'
  image: 127.0.0.1:5001/library/paas/nacos/nacos-server:1.4.1
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  database:
    type: mysql
    mysqlHost: 127.0.0.1
    mysqlDb: nacos_1
    mysqlUser: root
    mysqlPort: "3306"
    mysqlPassword: "12"
  readinessProbe:
    httpGet:
      path: /nacos/v1/console/health/liveness
      port: 8848
  config: |
    management.endpoints.web.exposure.include=*
